"""initial schema

Revision ID: 0698c026383a
Revises: 
Create Date: 2026-04-03 16:04:40.442716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0698c026383a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Numeric(), nullable=False),
    sa.Column('price_semiannual', sa.Numeric(), nullable=True),
    sa.Column('price_annual', sa.Numeric(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('max_accounts', sa.Integer(), nullable=True),
    sa.Column('cashback_percent', sa.Numeric(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('affiliate_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('commission_percent', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_referrals', sa.Integer(), nullable=True),
    sa.Column('total_earnings', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('target_client_id', sa.UUID(), nullable=True),
    sa.Column('show_banner', sa.Boolean(), nullable=True),
    sa.Column('send_email', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['target_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crm_leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('priority', sa.Text(), nullable=True),
    sa.Column('budget', sa.Text(), nullable=True),
    sa.Column('authority', sa.Text(), nullable=True),
    sa.Column('need', sa.Text(), nullable=True),
    sa.Column('timeline', sa.Text(), nullable=True),
    sa.Column('bant_score', sa.Integer(), nullable=True),
    sa.Column('telegram_username', sa.Text(), nullable=True),
    sa.Column('whatsapp', sa.Text(), nullable=True),
    sa.Column('wechat', sa.Text(), nullable=True),
    sa.Column('linkedin', sa.Text(), nullable=True),
    sa.Column('instagram', sa.Text(), nullable=True),
    sa.Column('discord', sa.Text(), nullable=True),
    sa.Column('monthly_budget', sa.Numeric(), nullable=True),
    sa.Column('company_size', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('interested_platforms', sa.JSON(), nullable=True),
    sa.Column('assigned_bdm_id', sa.UUID(), nullable=True),
    sa.Column('converted_client_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('custom_fields', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_bdm_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['converted_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_method', sa.Text(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('fee_percent', sa.Numeric(), nullable=True),
    sa.Column('fee_fixed', sa.Numeric(), nullable=True),
    sa.Column('min_amount', sa.Numeric(), nullable=True),
    sa.Column('max_amount', sa.Numeric(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('target_type', sa.Text(), nullable=False),
    sa.Column('target_value', sa.Numeric(), nullable=False),
    sa.Column('achieved_value', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('balance', sa.Numeric(), nullable=True),
    sa.Column('frozen_balance', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affiliate_referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_code_id', sa.UUID(), nullable=False),
    sa.Column('referred_client_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('total_commission', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_code_id'], ['affiliate_codes.id'], ),
    sa.ForeignKeyConstraint(['referred_client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_ad_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ad_account_id', sa.UUID(), nullable=False),
    sa.Column('meta_account_id', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('business_manager_id', sa.Text(), nullable=True),
    sa.Column('facebook_page_id', sa.Text(), nullable=True),
    sa.Column('instagram_account_id', sa.Text(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_account_id'], ['ad_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('fee', sa.Numeric(), nullable=True),
    sa.Column('net_amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.Text(), nullable=True),
    sa.Column('payment_reference', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affiliate_commissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_code_id', sa.UUID(), nullable=False),
    sa.Column('referral_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('source_transaction_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_code_id'], ['affiliate_codes.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['affiliate_referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meta_ad_account_id', sa.UUID(), nullable=False),
    sa.Column('meta_campaign_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('special_ad_categories', sa.JSON(), nullable=True),
    sa.Column('buying_type', sa.Text(), nullable=True),
    sa.Column('budget_optimization', sa.Text(), nullable=True),
    sa.Column('daily_budget', sa.Numeric(), nullable=True),
    sa.Column('lifetime_budget', sa.Numeric(), nullable=True),
    sa.Column('bid_strategy', sa.Text(), nullable=True),
    sa.Column('bid_amount', sa.Numeric(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('spend', sa.Numeric(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('ctr', sa.Numeric(), nullable=True),
    sa.Column('cpc', sa.Numeric(), nullable=True),
    sa.Column('cpm', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meta_ad_account_id'], ['meta_ad_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_ad_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('meta_adset_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('daily_budget', sa.Numeric(), nullable=True),
    sa.Column('lifetime_budget', sa.Numeric(), nullable=True),
    sa.Column('bid_strategy', sa.Text(), nullable=True),
    sa.Column('bid_amount', sa.Numeric(), nullable=True),
    sa.Column('optimization_goal', sa.Text(), nullable=True),
    sa.Column('billing_event', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('targeting', sa.JSON(), nullable=True),
    sa.Column('placements', sa.JSON(), nullable=True),
    sa.Column('spend', sa.Numeric(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['meta_campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_ads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ad_set_id', sa.UUID(), nullable=False),
    sa.Column('meta_ad_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('creative', sa.JSON(), nullable=True),
    sa.Column('format', sa.Text(), nullable=True),
    sa.Column('facebook_page_id', sa.Text(), nullable=True),
    sa.Column('instagram_account_id', sa.Text(), nullable=True),
    sa.Column('url_parameters', sa.Text(), nullable=True),
    sa.Column('tracking_specs', sa.JSON(), nullable=True),
    sa.Column('spend', sa.Numeric(), nullable=True),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('clicks', sa.BigInteger(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ad_set_id'], ['meta_ad_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_ads')
    op.drop_table('meta_ad_sets')
    op.drop_table('meta_campaigns')
    op.drop_table('affiliate_commissions')
    op.drop_table('wallet_transactions')
    op.drop_table('meta_ad_accounts')
    op.drop_table('affiliate_referrals')
    op.drop_table('wallets')
    op.drop_table('team_targets')
    op.drop_table('deposit_configs')
    op.drop_table('crm_leads')
    op.drop_table('alerts')
    op.drop_table('affiliate_codes')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
